version: "3"
services:
  protoc:
    build:
      context: .
      dockerfile: "protoc.Dockerfile"
      args:
        - "ARCH=aarch_64"
    platform: linux/amd64
    volumes:
      - ".:/ts-proto"
      - "${PWD:-.}:/host"
